name: Deploy Application

on:
  push:
    branches: [master]

jobs:
  nuxt-publishing:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2

      - name: command 1
        run: rm -rf  /home/motalebi/shayan.motalebi.me/* && rm -rf  /home/motalebi/shayan.motalebi.me/*.*
      - name: command 2
        run: cp -r /home/motalebi/actions-runner/_work/my-resume/my-resume/dist/. /home/motalebi/shayan.motalebi.me
      - name: command 3
        run: rm -rf /home/motalebi/actions-runner/_work/my-resume/my-resume/* && rm -rf /home/motalebi/actions-runner/_work/my-resume/my-resume/*.*
